import '@/styles/globals.css';

import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { KumaRegistry } from '@kuma-ui/next-plugin/registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  );
}
